services:
  debezium:
    build:
      context: ./debezium_image
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - ./.devenv/debezium_conf:/debezium/conf
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka
      - sqlserver
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rootroot1.
    ports:
      - 1433:1433
    volumes:
      - ./.devenv/sqlserver_conf:/usr/config
    entrypoint:
      - /usr/config/entrypoint.sh

  zookeeper:
    image: 'bitnami/zookeeper:3.8.1'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      restart_policy:
        condition: unless-stopped

  kafka:
    image: 'bitnami/kafka:3.3'
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper
    deploy:
      restart_policy:
        condition: unless-stopped

  mapper:
    build:
      context: ./mapper
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: unless-stopped
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: foo
      KAFKA_TOPIC: domainA.yerelservis.dbo.tblJobMaster
      POSTGRES_DATA_SOURCE: host=external-db port=5432 user=postgres password=postgres dbname=postgres sslmode=disable

  external-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - ./.devenv/postgres_conf:/docker-entrypoint-initdb.d

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - debezium
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium:8083
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
